---
- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer
  when: php_composer == true

- name: Install PHP Copy/Paste Detector
  get_url: url=https://phar.phpunit.de/phpcpd.phar dest=/usr/local/bin/phpcpd owner=root group=root mode=0755
  when: php_phpcpd == true

- name: Install PHP Code Sniffer
  get_url: url=https://squizlabs.github.io/PHP_CodeSniffer/{{ item }}.phar dest=/usr/local/bin/{{ item }} owner=root group=root mode=0755
  with_items:
    - phpcs
    - phpcbf
  when: php_phpcs == true

- name: Install PHP Depend
  get_url: url=http://static.pdepend.org/php/latest/pdepend.phar dest=/usr/local/bin/pdepend owner=root group=root mode=0755
  when: php_pdepend == true

- name: Install PHP Documentor
  get_url: url=http://phpdoc.org/phpDocumentor.phar dest=/usr/local/bin/phpdoc owner=root group=root mode=0755
  when: php_phpdoc == true

- name: Install PHP LOC
  get_url: url=https://phar.phpunit.de/phploc.phar dest=/usr/local/bin/phploc owner=root group=root mode=0755
  when: php_phploc == true

- name: Install PHP Mess Detector
  get_url: url=http://static.phpmd.org/php/latest/phpmd.phar dest=/usr/local/bin/phpmd owner=root group=root mode=0755
  when: php_phpmd == true

- name: Install PHPUnit
  get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit owner=root group=root mode=0755
  when: php_phpunit == true